#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=backone_waf_worker
PROG=/usr/bin/backone_waf_worker

start_service() {
        procd_open_instance
        procd_set_param command "$PROG"
        procd_close_instance
}

reload_service() {
        procd_send_signal $PROG
}

